### ISSUE TITLE
About Function Calling 

### ISSUE THREAD

**Issue by ZhaoKangkang0572** [Stephen-SMJ/LAMBDA#1]
Thanks for sharing. Fascinating job.

I noticed that you have investigated the impact of the number of APIs on accuracy. Have you already found some solutions to ease this situation or a plan for future work?

Thanks.

**Comment by Stephen-SMJ** [comment]
Thanks for your question. A potential solution is to make the API a hierarchical structure so that we can control the number of APIs in the final choices.
